#ifndef TABLE_PARAGRAPHS_H
#define TABLE_PARAGRAPHS_H

extern const char* DDL_CREATE_TABLE_IF_NOT_EXISTS_PARAGRAPHS;

extern const char* DMC_ANALYZE_PARAGRAPHS;

extern const char* DML_INSERT_PARAGRAPH;

extern const char* DML_SELECT_ORIGINAL_TEXT_FROM_PARAGRAPHS_WHERE_ID_EQUALS;

extern const char* DML_SELECT_ORIGINAL_TEXT_FROM_PARAGRAPHS_WHERE_ID_EQUALS_PART_1;

extern const char* DML_SELECT_ORIGINAL_TEXT_FROM_PARAGRAPHS_WHERE_ID_EQUALS_PART_2;

#endif