#ifndef TABLE_WORDS_TO_PARAGRAPHS_H
#define TABLE_WORDS_TO_PARAGRAPHS_H

extern const char* DDL_CREATE_TABLE_IF_NOT_EXISTS_WORDS_TO_PARAGRAPHS;

extern const char* DMC_ANALYZE_WORDS_TO_PARAGRAPHS;

extern const char* DML_INSERT_WORD_TO_PARAGRAPH;

extern const char* DML_SELECT_COMPOUND_1_EQUALS;

extern const char* DML_SELECT_COMPOUND_1_LIKE;

#endif