#ifndef TABLE_WORDS_H
#define TABLE_WORDS_H

extern const char* DDL_CREATE_TABLE_IF_NOT_EXISTS_WORDS;

extern const char* DMC_ANALYZE_WORDS;

extern const char* DML_INSERT_WORD;

extern const char* DML_EXPLAIN_QUERY_PLAN_DML_SELECT_ID_FROM_WORDS_WHERE_WORD_EQUALS;

extern const char* DML_SELECT_ID_FROM_WORDS_WHERE_WORD_EQUALS;

extern const char* DML_EXPLAIN_QUERY_PLAN_DML_SELECT_ID_FROM_WORDS_WHERE_WORD_LIKE;

extern const char* DML_SELECT_ID_FROM_WORDS_WHERE_WORD_LIKE;

extern const char* DML_SELECT_ID_WORD_FROM_WORDS_WHERE_WORD_EQUALS;

extern const char* DML_SELECT_ID_WORD_FROM_WORDS_WHERE_WORD_LIKE;

#endif
